# Generated by Django 2.0.2 on 2018-03-01 15:46

import core.models.user
from django.db import migrations, models
import django_countries.fields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=2, max_length=50, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1994-09-29', verbose_name='birth date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(default='066824673', max_length=20, verbose_name='cell phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Banja Luka', max_length=30, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='BA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='desk_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='desk phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='home phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='home phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether the user is manager or not.', verbose_name='manager status'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=30, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='sjshhsk', upload_to=core.models.user.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state_province',
            field=models.CharField(blank=True, max_length=50, verbose_name='state province'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(default='678888', max_length=20, verbose_name='zip'),
            preserve_default=False,
        ),
    ]
