# Generated by Django 2.0.4 on 2018-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180518_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default='1990-01-01', verbose_name='birth date'),
        ),
    ]
