# Generated by Django 2.0.4 on 2018-06-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vacationemployee_vacationused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_set', to='core.Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_set', to='core.Office'),
        ),
    ]
