# Generated by Django 2.0.4 on 2018-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180613_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationemployee',
            name='vacation_remainder',
            field=models.PositiveIntegerField(default=25, verbose_name='vacation_remainder'),
        ),
    ]
