# Generated by Django 2.0.4 on 2018-06-20 18:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180614_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchin', models.DateTimeField(default=datetime.datetime(2018, 6, 20, 18, 12, 23, tzinfo=utc), verbose_name='check_in')),
                ('punchout', models.DateTimeField(null=True, verbose_name='check_out')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
